theme: jekyll-theme-midnight
title: Dr. Anish Mallick
tagline: Staff Data Scientist (PhD Mathematical Physics)
description: Personal portfolio and research index of Dr. Anish Mallick, Staff Data Scientist and Mathematical Physicist.
url: "https://anish23618.github.io"
author: Dr. Anish Mallick
plugins:
  - jekyll-seo-tag
